### ISSUE TITLE
Figure out how Twitch sends "whispers" or private messages.

### ISSUE THREAD

**Issue by calledtoconstruct** [calledtoconstruct/lambdabot#19]
Currently, PRIVMSG is used within the channel, so it works differently than IRC, I believe.

**Comment by Andrewnetwork** [comment]
May not be possible, see: https://discuss.dev.twitch.tv/t/private-message-api-support/9483/5

**Comment by Andrewnetwork** [comment]
It's possible to to send whispers to users, but not to receive them as a bot. Twitch uses /w <user> <message> to send whispers, but that lies outside IRC. There is currently no API available to access your private messages. The only solution, it seems, would be to have a headless browser login to twitch as the bot and grab the messages through the web UI.

**Comment by Andrewnetwork** [comment]
Some more posts about this: 

- https://discuss.dev.twitch.tv/t/have-a-chat-whisper-bot-let-us-know/10651

- https://discuss.dev.twitch.tv/t/i-cant-send-whisper-to-a-user-from-irc/10753
